---
- name: Appli common configurations all roles
  hosts: all
  user: vagrant
  sudo: yes
  roles:
    - common

- hosts: webservers
  user: vagrant
  sudo: yes
  roles:
    - nginx
    - mysql
    - php7
    - phalcon